name: Build .NET 6

env:
  DOTNET_VERSION: "6.0.x"

on: 
  push:
    branches:
      - "master"

jobs:
  build:
    environment: "production"
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build release
        run: dotnet build --configuration Release
      - name: Publish application (Windows)
        run: dotnet publish -c Release -r win-x64 -p:PublishReadyToRun=true -p:PublishSingleFile=true --self-contained true
      - name: Publish application (Linux)
        run: dotnet publish -c Release -r linux-x64 -p:PublishReadyToRun=true -p:PublishSingleFile=true --self-contained true
      - name: Archive windows
        uses: actions/upload-artifact@v3
        with:
            name: docker-host-writer-windows-${{ github.sha }}-unsigned
            path: bin/Release/net6.0/win-x64/publish/
            if-no-files-found: error
      - name: Archive linux
        uses: actions/upload-artifact@v3
        with:
            name: docker-host-writer-linux-${{ github.sha }}
            path: bin/Release/net6.0/win-x64/publish/
            if-no-files-found: error